# Generated by Django 4.2.11 on 2025-12-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity to trigger this discount', unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-min_quantity'],
            },
        ),
    ]
