# Generated by Django 4.2.11 on 2025-12-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricingtier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Alt text for the image', max_length=100)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PrintHive Kenya', max_length=100)),
                ('logo', models.ImageField(help_text='Main website logo', upload_to='site/')),
                ('phone_contact', models.CharField(default='+254 746 336 276', help_text='Primary contact phone', max_length=20)),
                ('whatsapp_number', models.CharField(default='+254746336276', help_text='Number for WhatsApp links (no spaces/+)', max_length=20)),
                ('email_contact', models.EmailField(default='studioprinthive@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Facebook, Instagram', max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Feather icon name (e.g., facebook, instagram)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
